### ISSUE TITLE
[Refac] UserTask, StudyGroup 코드 추가

### ISSUE THREAD

**Issue by JuHyeonAh** [TeamSwith/Server#54]
## 📌 이슈명
UserTask, StudyGroup 코드 추가

## ✅ To-do
1. User
- [x] taskid 추가
- [x] 객체 생성 메서드
- [x] 객체 삭제 메서드

2. StudyGroup
- [x] Study도 함께 삭제되도록 수정
